### ISSUE TITLE
BROWSE | FRONTEND: Update the action items for steps 1-3 to: 1. Add a book (this should open the Add a Book modal), 2. Browse for books to borrow (this should pop up a Search modal), 3. Borrow a book (this should open the Borrow modal)

### ISSUE THREAD

**Issue by makeithappenmike** [VaishaliQA/Novelty_Project#32]

**Comment by isayani** [comment]
@makeithappenmike  while you're doing this, can you fix the small small change to the 'browse' 'library' and 'logout' tabs? Maybe you already had this on docket, but changing the color based on which tab you're on. Selected tab should be same color as border and other tabs would be a shade darker.
